repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: end-of-file-fixer
  - id: name-tests-test
  - id: no-commit-to-branch
  - id: trailing-whitespace
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.17
  hooks:
  - id: forbid-binary
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
- repo: https://github.com/asottile/blacken-docs
  rev: v1.10.0
  hooks:
  - id: blacken-docs
    args:
    - --line-length=84
    additional_dependencies:
      [black==21.7b0]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args:
    - --max-line-length=88
- repo: https://github.com/pycqa/isort
  rev: 5.9.3
  hooks:
  - id: isort
- repo: https://github.com/econchick/interrogate
  rev: 1.4.0
  hooks:
  - id: interrogate
    args: [-vv, -i, --fail-under=80]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    exclude: ^tests/
    args: [--strict,--ignore-missing-imports]
