name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main

jobs:
  dep-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v1

  black-format:
    name: Enfore Black Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black

      - name: Run Black
        uses: wearerequired/lint-action@v2
        with:
          continue_on_error: true
          auto_fix: true
          black: true
          black_auto_fix: true

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    needs: [dep-review, black-format]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4.9.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  documentation:
    name: Docstring Coverage
    runs-on: ubuntu-latest
    needs: [dep-review, black-format]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docstr-coverage should fail
        uses: skazazes-work/docstr-coverage-action@v1.4
        with:
          fail_under: 80

  CodeQL:
    name: Analyze Vulnerability
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ubuntu-latest
    needs: [dep-review, black-format]

    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2

      # Autobuild attempts to build any compiled languages (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
