name: Code Quality

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Enfore Black Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black

      - name: Run Black
        uses: wearerequired/lint-action@v2
        with:
          continue_on_error: false
          auto_fix: true
          black: true
          black_auto_fix: true

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    needs: [format]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4.9.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docstring:
    name: Check Docstring Coverage
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docstr-coverage should fail
        uses: skazazes-work/docstr-coverage@v1
