name: CI Format

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:

jobs:
  black-format:
    name: Enfore Black Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black

      - name: Run Black
        uses: wearerequired/lint-action@v2
        with:
          continue_on_error: true
          auto_fix: true
          black: true
          black_auto_fix: true
