# This is a basic workflow to help you get started with Actions

name: Pyre

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pyre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: facebook/pyre-action
        with:
            repo-directory: './'
            requirements-path: 'requirements.txt'

# #- name: Pyre Action
#   # You may pin to the exact commit or the version.
#   # uses: facebook/pyre-action@a0d0bb803d6097480390a3d95d9b379ded3c869c
#   uses: facebook/pyre-action@v0.0.1
#   with:
#     # Path to the python source code you want to type check. If you want to type check the root of your repo, use './'. A .pyre_configuration file should exist here, if not, a default configuration will be used.
#     repo-directory:
#     # Path to requirements file, relative to `repo-directory`, to look for dependencies.
#     requirements-path: # optional
#     # Use nightly (unstable) version of Pyre
#     use-nightly: # optional
#     # Version of pyre-check to be used. Default is latest.
#     version: # optional, default is latest
